/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones = 'Asia/Seoul';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    posts: Post;
    categories: Category;
    search: Search;
    redirects: Redirect;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  /**
   * Author name shown on posts and structured data.
   */
  name?: string | null;
  /**
   * Short public bio used for author structured data.
   */
  bio?: string | null;
  /**
   * Public profile image for author rich results and bylines.
   */
  profileImage?: (string | null) | Media;
  /**
   * Public website URL for this author.
   */
  website?: string | null;
  githubUrl?: string | null;
  totpSecret?: string | null;
  hasTotp?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * 이미지를 볼 수 없어도 같은 정보를 이해할 수 있게 핵심 의미를 설명하세요.
   */
  alt: string;
  /**
   * 이미지 출처, 맥락, 추가 설명이 필요할 때 입력하세요.
   */
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  /**
   * 브라우저 제목과 구조화 데이터의 기준입니다. 화면에 보이는 제목은 히어로 블록에서 작성하세요.
   */
  title: string;
  /**
   * 위에서 아래 순서대로 공개 페이지에 표시됩니다.
   */
  blocks?:
    | (
        | HighImpactHeroBlock
        | MediumImpactHeroBlock
        | LowImpactHeroBlock
        | CallToActionBlock
        | ContentBlock
        | MediaBlock
        | ArchiveBlock
      )[]
    | null;
  meta?: {
    title?: string | null;
    /**
     * 검색 결과와 공유 카드에 표시됩니다. 1200×630 비율의 이미지를 권장합니다.
     */
    image?: (string | null) | Media;
    /**
     * 일반적으로 자동 URL을 사용합니다. 외부 원문이 있을 때만 직접 지정하세요.
     */
    canonicalUrl?: string | null;
    description?: string | null;
  };
  /**
   * 비워 두고 발행하면 현재 시각이 기록됩니다. 예약 발행은 별도 예약 기능을 사용하세요.
   */
  publishedAt?: string | null;
  /**
   * 공개 URL 경로에 사용됩니다. 직접 수정하려면 잠금을 해제하세요.
   */
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HighImpactHeroBlock".
 */
export interface HighImpactHeroBlock {
  /**
   * 페이지 최상단의 배경 이미지 위에 제목과 소개 문구로 표시됩니다.
   */
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * 히어로 문구 아래에 표시할 버튼을 최대 2개 추가하세요.
   */
  links?:
    | {
        /**
         * 독자가 이동할 대상과 화면에 보이는 문구를 설정합니다.
         */
        link: {
          /**
           * 사이트 내부 문서인지 직접 입력할 URL인지 선택하세요.
           */
          type?: ('reference' | 'custom') | null;
          /**
           * 현재 페이지를 유지해야 하는 외부 링크에 사용하세요.
           */
          newTab?: boolean | null;
          /**
           * 사이트 안의 페이지나 게시글로 연결합니다.
           */
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null);
          /**
           * 외부 사이트 주소 또는 직접 관리하는 경로를 입력하세요.
           */
          url?: string | null;
          /**
           * 버튼이나 텍스트 링크에 독자가 보는 문구입니다.
           */
          label: string;
          /**
           * 공개 페이지에서 링크가 보이는 스타일을 선택하세요.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * 페이지 최상단 전체 너비에 표시됩니다. 문구가 읽히는 이미지를 선택하세요.
   */
  media: string | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'HighImpactHero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: string;
  /**
   * 게시글 목록, 브라우저 제목, 공유 카드 생성의 기준입니다.
   */
  title: string;
  /**
   * 목록과 검색 설명에 사용할 1~2문장 요약입니다. 결론과 대상 독자를 포함하세요.
   */
  summary: string;
  /**
   * 자동 집계되며 직접 수정할 수 없습니다.
   */
  views?: number | null;
  /**
   * 게시글에 연결할 대표 이미지입니다. SEO 탭의 검색·공유 이미지 자동 생성에도 사용됩니다.
   */
  heroImage?: (string | null) | Media;
  /**
   * 게시글 제목이 H1입니다. 본문은 H2부터 시작하세요.
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * 본문을 읽은 뒤 이어서 볼 글을 최대 3개 선택하세요.
   */
  relatedPosts?: (string | Post)[] | null;
  meta?: {
    title?: string | null;
    /**
     * 자동 생성하면 게시글의 대표 이미지를 사용합니다. 직접 다른 이미지를 선택할 수도 있습니다.
     */
    image?: (string | null) | Media;
    /**
     * 자동 생성하면 현재 URL 슬러그를 사용합니다. 외부 원문이 있을 때는 직접 입력하세요.
     */
    canonicalUrl?: string | null;
    description?: string | null;
  };
  /**
   * 비워 두고 발행하면 현재 시각이 기록됩니다. 예약 발행은 별도 예약 기능을 사용하세요.
   */
  publishedAt?: string | null;
  /**
   * 독자에게 의미 있는 본문 변경일이며 자동으로 관리됩니다.
   */
  contentUpdatedAt?: string | null;
  /**
   * 공개 바이라인과 구조화 데이터에 표시됩니다.
   */
  authors?: (string | User)[] | null;
  /**
   * 가장 관련성이 높은 카테고리만 선택하세요.
   */
  categories?: (string | Category)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
        bio?: string | null;
        website?: string | null;
        githubUrl?: string | null;
        profileImage?: (string | null) | Media;
      }[]
    | null;
  /**
   * 공개 URL 경로에 사용됩니다. 직접 수정하려면 잠금을 해제하세요.
   */
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  title: string;
  /**
   * 공개 URL 경로에 사용됩니다. 직접 수정하려면 잠금을 해제하세요.
   */
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediumImpactHeroBlock".
 */
export interface MediumImpactHeroBlock {
  /**
   * 페이지 상단에서 대표 이미지 위에 제목과 소개 문구로 표시됩니다.
   */
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * 히어로 문구 아래에 표시할 버튼을 최대 2개 추가하세요.
   */
  links?:
    | {
        /**
         * 독자가 이동할 대상과 화면에 보이는 문구를 설정합니다.
         */
        link: {
          /**
           * 사이트 내부 문서인지 직접 입력할 URL인지 선택하세요.
           */
          type?: ('reference' | 'custom') | null;
          /**
           * 현재 페이지를 유지해야 하는 외부 링크에 사용하세요.
           */
          newTab?: boolean | null;
          /**
           * 사이트 안의 페이지나 게시글로 연결합니다.
           */
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null);
          /**
           * 외부 사이트 주소 또는 직접 관리하는 경로를 입력하세요.
           */
          url?: string | null;
          /**
           * 버튼이나 텍스트 링크에 독자가 보는 문구입니다.
           */
          label: string;
          /**
           * 공개 페이지에서 링크가 보이는 스타일을 선택하세요.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * 히어로 문구 아래에 페이지 대표 이미지로 표시됩니다.
   */
  media: string | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'MediumImpactHero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LowImpactHeroBlock".
 */
export interface LowImpactHeroBlock {
  /**
   * 페이지 상단의 좁은 본문 영역에 제목과 소개 문구로 표시됩니다.
   */
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * 공개 페이지에 표시할 순서대로 링크를 추가하세요.
   */
  links?:
    | {
        /**
         * 독자가 이동할 대상과 화면에 보이는 문구를 설정합니다.
         */
        link: {
          /**
           * 사이트 내부 문서인지 직접 입력할 URL인지 선택하세요.
           */
          type?: ('reference' | 'custom') | null;
          /**
           * 현재 페이지를 유지해야 하는 외부 링크에 사용하세요.
           */
          newTab?: boolean | null;
          /**
           * 사이트 안의 페이지나 게시글로 연결합니다.
           */
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null);
          /**
           * 외부 사이트 주소 또는 직접 관리하는 경로를 입력하세요.
           */
          url?: string | null;
          /**
           * 버튼이나 텍스트 링크에 독자가 보는 문구입니다.
           */
          label: string;
          /**
           * 공개 페이지에서 링크가 보이는 스타일을 선택하세요.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'LowImpactHero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  /**
   * 독자의 다음 행동을 안내하는 문구로 버튼 옆에 표시됩니다.
   */
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * 공개 페이지에 표시할 버튼을 최대 2개 추가하세요.
   */
  links?:
    | {
        /**
         * 독자가 이동할 대상과 화면에 보이는 문구를 설정합니다.
         */
        link: {
          /**
           * 사이트 내부 문서인지 직접 입력할 URL인지 선택하세요.
           */
          type?: ('reference' | 'custom') | null;
          /**
           * 현재 페이지를 유지해야 하는 외부 링크에 사용하세요.
           */
          newTab?: boolean | null;
          /**
           * 사이트 안의 페이지나 게시글로 연결합니다.
           */
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null);
          /**
           * 외부 사이트 주소 또는 직접 관리하는 경로를 입력하세요.
           */
          url?: string | null;
          /**
           * 버튼이나 텍스트 링크에 독자가 보는 문구입니다.
           */
          label: string;
          /**
           * 공개 페이지에서 링크가 보이는 스타일을 선택하세요.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  /**
   * 데스크톱에서는 선택한 너비로 배치되고 모바일에서는 세로로 이어집니다.
   */
  columns?:
    | {
        /**
         * 데스크톱 화면에서 이 열이 차지할 너비입니다.
         */
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        /**
         * 해당 열의 본문으로 공개 페이지에 표시됩니다.
         */
        richText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        /**
         * 이 열 아래에 이동 링크를 표시할 때 선택하세요.
         */
        enableLink?: boolean | null;
        /**
         * 열의 내용을 읽은 뒤 이동할 대상을 설정합니다.
         */
        link?: {
          /**
           * 사이트 내부 문서인지 직접 입력할 URL인지 선택하세요.
           */
          type?: ('reference' | 'custom') | null;
          /**
           * 현재 페이지를 유지해야 하는 외부 링크에 사용하세요.
           */
          newTab?: boolean | null;
          /**
           * 사이트 안의 페이지나 게시글로 연결합니다.
           */
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null);
          /**
           * 외부 사이트 주소 또는 직접 관리하는 경로를 입력하세요.
           */
          url?: string | null;
          /**
           * 버튼이나 텍스트 링크에 독자가 보는 문구입니다.
           */
          label: string;
          /**
           * 공개 페이지에서 링크가 보이는 스타일을 선택하세요.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  /**
   * 선택한 미디어와 캡션이 본문 또는 페이지의 한 구역으로 표시됩니다.
   */
  media: string | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock".
 */
export interface ArchiveBlock {
  /**
   * 선택한 글 목록 바로 위에 표시됩니다.
   */
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * 조건으로 자동 구성하거나 글을 직접 선택할 수 있습니다.
   */
  populateBy?: ('collection' | 'selection') | null;
  /**
   * 현재는 게시글 목록만 지원합니다.
   */
  relationTo?: 'posts' | null;
  /**
   * 선택한 카테고리에 속한 글만 표시합니다. 비워 두면 모든 카테고리를 대상으로 합니다.
   */
  categories?: (string | Category)[] | null;
  /**
   * 공개 페이지에 표시할 최대 글 개수입니다.
   */
  limit?: number | null;
  /**
   * 선택한 순서대로 공개 페이지에 표시됩니다.
   */
  selectedDocs?:
    | {
        relationTo: 'posts';
        value: string | Post;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'archive';
}
/**
 * 공개 게시글의 제목과 요약으로 자동 생성되는 검색 인덱스입니다.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: string;
  title?: string | null;
  priority?: number | null;
  doc: {
    relationTo: 'posts';
    value: string | Post;
  };
  summary?: string | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: string;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: string | Post;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: string | Post;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'search';
        value: string | Search;
      } | null)
    | ({
        relationTo: 'redirects';
        value: string | Redirect;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  bio?: T;
  profileImage?: T;
  website?: T;
  githubUrl?: T;
  totpSecret?: T;
  hasTotp?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  blocks?:
    | T
    | {
        HighImpactHero?: T | HighImpactHeroBlockSelect<T>;
        MediumImpactHero?: T | MediumImpactHeroBlockSelect<T>;
        LowImpactHero?: T | LowImpactHeroBlockSelect<T>;
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        canonicalUrl?: T;
        description?: T;
      };
  publishedAt?: T;
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HighImpactHeroBlock_select".
 */
export interface HighImpactHeroBlockSelect<T extends boolean = true> {
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  media?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediumImpactHeroBlock_select".
 */
export interface MediumImpactHeroBlockSelect<T extends boolean = true> {
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  media?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LowImpactHeroBlock_select".
 */
export interface LowImpactHeroBlockSelect<T extends boolean = true> {
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock_select".
 */
export interface ArchiveBlockSelect<T extends boolean = true> {
  introContent?: T;
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  summary?: T;
  views?: T;
  heroImage?: T;
  content?: T;
  relatedPosts?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        canonicalUrl?: T;
        description?: T;
      };
  publishedAt?: T;
  contentUpdatedAt?: T;
  authors?: T;
  categories?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
        bio?: T;
        website?: T;
        githubUrl?: T;
        profileImage?: T;
      };
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  summary?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: string;
  navItems?:
    | {
        /**
         * 독자가 이동할 대상과 화면에 보이는 문구를 설정합니다.
         */
        link: {
          /**
           * 사이트 내부 문서인지 직접 입력할 URL인지 선택하세요.
           */
          type?: ('reference' | 'custom') | null;
          /**
           * 현재 페이지를 유지해야 하는 외부 링크에 사용하세요.
           */
          newTab?: boolean | null;
          /**
           * 사이트 안의 페이지나 게시글로 연결합니다.
           */
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null);
          /**
           * 외부 사이트 주소 또는 직접 관리하는 경로를 입력하세요.
           */
          url?: string | null;
          /**
           * 버튼이나 텍스트 링크에 독자가 보는 문구입니다.
           */
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  navItems?:
    | {
        /**
         * 독자가 이동할 대상과 화면에 보이는 문구를 설정합니다.
         */
        link: {
          /**
           * 사이트 내부 문서인지 직접 입력할 URL인지 선택하세요.
           */
          type?: ('reference' | 'custom') | null;
          /**
           * 현재 페이지를 유지해야 하는 외부 링크에 사용하세요.
           */
          newTab?: boolean | null;
          /**
           * 사이트 안의 페이지나 게시글로 연결합니다.
           */
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null);
          /**
           * 외부 사이트 주소 또는 직접 관리하는 경로를 입력하세요.
           */
          url?: string | null;
          /**
           * 버튼이나 텍스트 링크에 독자가 보는 문구입니다.
           */
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: string | Post;
        } | null);
    global?: string | null;
    user?: (string | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  /**
   * 공개 본문에서 의미에 맞는 아이콘과 색상으로 표시됩니다.
   */
  style: 'info' | 'warning' | 'error' | 'success';
  /**
   * 본문에서 독자가 놓치지 않아야 할 내용을 강조해 표시합니다.
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}